manifest:
  remotes:
    - name: talf301
      url-base: https://github.com/talf301
  projects:
    - name: zmk
      remote: talf301
      revision: repeatrollfix-tapdance-macro-mouse-dongle
      import: app/west.yml
  self:
    path: config
